[ch127801] Country conversion to ISO code in TomTom bulk geocoding
CartoDB/dataservices-api pull request #614
Opened 2021-01-26 15:27 UTC by Shylpx

### Resources

- [Clubhouse story](https://app.clubhouse.io/cartoteam/story/127801/fix-countryset-for-tomtom-geocoding)

### Context

- The TomTom requests require the country param (`countrySet`) as a ISO code, according to the TomTom documentation:
![Screenshot from 2021-01-26 15-19-28](https://user-images.githubusercontent.com/6042873/105865343-c1013580-5fea-11eb-982f-b6a9b55cc0f9.png)
- There are two different methods for geocoding using TomTom provider:
  - [_cdb_tomtom_geocode_street_point](https://github.com/CartoDB/dataservices-api/blob/d3720d6953e9435d43972c798ce1ba3e3c56f6e0/server/extension/cdb_dataservices_server--0.39.2.sql#L2270): Single address geocoding.
  - [_cdb_bulk_tomtom_geocode_street_point](https://github.com/CartoDB/dataservices-api/blob/d3720d6953e9435d43972c798ce1ba3e3c56f6e0/server/extension/cdb_dataservices_server--0.39.2.sql#L2518): Bulk address geocoding.
- So, when a country name is passed as a `country` param to those methods, it should be converted to restrict the results to that country. There is already a conversion in the first one using the `country_to_iso3` method, but while bulk geocoding, there is no conversion being performed.

### Changes

- Add a conversion from country name to ISO code in the TomTom bulk geocoder.

2021-01-27 09:14 UTC, Algunenano requested changes
PG12 tests seem broken. I think Infra did some changes to the base images so that might be way. It should be fixed before merging this.

2021-01-27 09:14 UTC, Algunenano commented on server/lib/python/cartodb_services/cartodb_services/tomtom/bulk_geocoder.py
> +            country = country_to_iso3(country) or country
You are only changing the serial geocoder of the bulk geocoder (I think it's used when the array passed to the bulk geocoder is small). I think this should be done in a common path.

2021-01-27 14:31 UTC, Shylpx commented on server/lib/python/cartodb_services/cartodb_services/tomtom/bulk_geocoder.py
> +            country = country_to_iso3(country) or country
The common path is the `_request_uri` method in the `TomTomGeocoder`. Since it is also being used by the `cdb_dataservices_server._cdb_tomtom_geocode_street_point`, I removed the existent conversion from that method to avoid a double conversion.

2021-01-27 14:32 UTC, Shylpx commented
I have asked infra in order to fix the PG12 build before merging.

2021-02-05 10:00 UTC, Algunenano approved these changes
Looks fine to me. Nice!

2021-02-08 09:53 UTC, merged